secure_witness/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),

    # login and logout
    url(r'^user/new/$', views.new_user, name='new_user'),
    url(r'^user/login/$', views.user_login, name='existing_user'),
    url(r'^user/logout/$', 'django.contrib.auth.views.logout', { 'next_page': 'home', }, name='logout'),

    # password reset
    url(r'^reset_password/$', 'django.contrib.auth.views.password_reset',  { 'post_reset_redirect' : '/reset_password/done/' }, name="password_reset"),
    (r'^reset_password/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', { 'post_reset_redirect' : '/reset_password/complete/' }, name="password_reset_confirm"),
    (r'^reset_password/complete/$', 'django.contrib.auth.views.password_reset_complete'),

    # model operations
    url(r'^folder/(?P<folder_id>\d+)/copy/$', views.copy_folder, name='copy_folder'),
    url(r'^folder/(?P<folder_id>\d+)/delete/$', views.delete_folder, name='delete_folder'),
    url(r'^folder/(?P<folder_id>\d+)/edit/$', views.edit_folder, name='edit_folder'),
    url(r'^folder/(?P<folder_id>\d+)/$', views.get_folder, name='get_folder'),
    url(r'^folder/new/$', views.new_folder, name='new_folder'),
    url(r'^bulletin/(?P<bulletin_id>\d+)/copy/$', views.copy_bulletin, name='copy_bulletin'),
    url(r'^bulletin/(?P<bulletin_id>\d+)/delete/$', views.delete_bulletin, name='delete_bulletin'),
    url(r'^bulletin/(?P<bulletin_id>\d+)/edit/$', views.edit_bulletin, name='edit_bulletin'),
    url(r'^bulletin/(?P<bulletin_id>\d+)/$', views.get_bulletin, name='get_bulletin'),
    url(r'^bulletin/(?P<bulletin_id>\d+)/comment/$', views.post_comment, name='post_comment'),
    url(r'^folder/(?P<folder_id>\d+)/bulletin/new/$', views.new_bulletin, name='new_bulletin'),
    url(r'^bulletin/(?P<bulletin_id>\d+)/file/new/$', views.new_file, name='new_file'),
    url(r'^bulletin/search/$', views.search_bulletins, name='search_bulletins'),
    url(r'^file/(?P<file_id>\d+)/$', views.get_file, name='get_file'),
    url(r'^file/(?P<file_id>\d+)/give_access/$', views.give_access, name='give_access'),
    url(r'^file/(?P<file_id>\d+)/delete/$', views.delete_file, name='delete_file'),
)

secure_witness/forms.py
from models import Folder, Bulletin, User
from django import forms
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput(),
    )
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class UploadFileForm(forms.Form):
    file = forms.FileField()
    encrypt = forms.CharField(
        required=False,
        max_length=128,
        label='Encryption password (leave blank to keep unencrypted)',
        widget=forms.PasswordInput(),
    )
    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ('name', 'location', 'description')
    required_css_class = 'required'
    name = forms.CharField(
        required = True,
        max_length = 128,
        label = 'Folder Name:',
        )
    location = forms.CharField(
        required = False,
        max_length = 128,
        label = 'Location:',
        )
    description = forms.CharField(
        required = False,
        max_length = 1024,
        label = 'Description:',
        widget = forms.Textarea(),
        )
    def __init__(self, *args, **kwargs):
        super(FolderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    def clean(self):
        return self.cleaned_data

class BulletinForm(forms.ModelForm):
    class Meta:
        model = Bulletin
        fields = ('name', 'location', 'description')
    required_css_class = 'required'
    name = forms.CharField(
        required = True,
        max_length = 128,
        label = 'Bulletin Name:',
        )
    location = forms.CharField(
        required = False,
        max_length = 128,
        label = 'Location:',
        )
    description = forms.CharField(
        required = False,
        max_length = 1024,
        label = 'Description:',
        widget = forms.Textarea(),
        )
    def __init__(self, *args, **kwargs):
        super(BulletinForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean(self):
        return self.cleaned_data

class BulletinSearchForm(forms.Form):
    CHAR_FIELD_CHOICES = (
        ('NO', ''),
        ('EQ', 'is exactly'),
        ('CT', 'contains'),
    )

    author_check = forms.ChoiceField(choices=CHAR_FIELD_CHOICES, required=False)
    author_username = forms.CharField(max_length=128, required=False)
    bulletin_check = forms.ChoiceField(choices=CHAR_FIELD_CHOICES, required=False)
    bulletin_name = forms.CharField(max_length=128, required=False)
    created_after_year = forms.IntegerField(required=False, min_value=1, max_value=9999)
    created_after_month = forms.IntegerField(required=False, min_value=1, max_value=12)
    created_after_day = forms.IntegerField(required=False, min_value=1, max_value=31)
    created_after_hour = forms.IntegerField(required=False, min_value=0, max_value=23)
    created_after_minute = forms.IntegerField(required=False, min_value=0, max_value=59)
    created_after_second = forms.IntegerField(required=False, min_value=0, max_value=59)
    created_before_year = forms.IntegerField(required=False, min_value=1, max_value=9999)
    created_before_month = forms.IntegerField(required=False, min_value=1, max_value=12)
    created_before_day = forms.IntegerField(required=False, min_value=1, max_value=31)
    created_before_hour = forms.IntegerField(required=False, min_value=0, max_value=23)
    created_before_minute = forms.IntegerField(required=False, min_value=0, max_value=59)
    created_before_second = forms.IntegerField(required=False, min_value=0, max_value=59)
    modified_after_year = forms.IntegerField(required=False, min_value=1, max_value=9999)
    modified_after_month = forms.IntegerField(required=False, min_value=1, max_value=12)
    modified_after_day = forms.IntegerField(required=False, min_value=1, max_value=31)
    modified_after_hour = forms.IntegerField(required=False, min_value=0, max_value=23)
    modified_after_minute = forms.IntegerField(required=False, min_value=0, max_value=59)
    modified_after_second = forms.IntegerField(required=False, min_value=0, max_value=59)
    modified_before_year = forms.IntegerField(required=False, min_value=1, max_value=9999)
    modified_before_month = forms.IntegerField(required=False, min_value=1, max_value=12)
    modified_before_day = forms.IntegerField(required=False, min_value=1, max_value=31)
    modified_before_hour = forms.IntegerField(required=False, min_value=0, max_value=23)
    modified_before_minute = forms.IntegerField(required=False, min_value=0, max_value=59)
    modified_before_second = forms.IntegerField(required=False, min_value=0, max_value=59)
    location_check = forms.ChoiceField(choices=CHAR_FIELD_CHOICES, required=False)
    location = forms.CharField(max_length=128, required=False)
    description_check = forms.ChoiceField(choices=CHAR_FIELD_CHOICES, required=False)
    description = forms.CharField(max_length=128, required=False)


class GiveAccessForm(forms.Form):
    reader = None
    author_password = forms.CharField(required=False, widget=forms.PasswordInput())

    def __init__(self, file, *args, **kwargs):
        super(GiveAccessForm, self).__init__(*args, **kwargs)
        self.fields['reader'] = forms.ModelMultipleChoiceField(queryset = User.objects.exclude(
            pk__in = file.fileaccess_set.values('reader__pk'),
        ))
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class CommentForm(forms.Form):
    text = forms.CharField(max_length = 128, widget = forms.Textarea(attrs={
        'placeholder': 'Have anything to say?',
        'rows': '4',
        'cols': '80',
    }))

secure_witness/templates/secure_witness/copy_bulletin.html
{% extends "base.html" %}

{% block center_content %}
{% load staticfiles %}
<!-- Custom styles for this template -->
<link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

<div class="container">

<div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Copy the bulletin {{bulletin.name}}</h2>
				<hr class="colorgraph">

				{% if bulletin_taken %}
				<div class="alert alert-danger" role="alert">Bulletin name already exists. Please try again.</div>
				{% endif %}
				{% if form.name.errors %}
				<div class="alert alert-danger" role="alert">The bulletin name is required. Please try again.</div>
				{% endif %}		

				<div class="form-group">
				  <label for="id_name">Bulletin Name*: </label>
				  <input class="form-control input-lg" id="id_name" maxlength="128" name="name" type="text" value="{{bulletin.name}}" required="required" 
					 {% if form.name.errors or bulletin_taken %} style="background:#ffdddd;" {% endif %}>
				</div>
				<div class="form-group">
				  <label for="id_location">Location:</label>
				  {{ form.location }}
				</div>
				<div class="form-group">
				  <label for="id_description">Description:</label>
				  {{ form.description }}
				</div>
				<hr class="colorgraph">
				    <input type="submit" class="btn btn-lg btn-primary btn-block" formaction="{% url 'copy_bulletin' bulletin_id %}" value="Copy bulletin">
			</fieldset>
		</form>
    </div>
</div>

</div>

{% endblock %}

secure_witness/templates/secure_witness/copy_folder.html
{% extends "base.html" %}

{% block center_content %}

{% load staticfiles %}
<!-- Custom styles for this template -->
<link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

<div class="container">

<div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Copy the folder {{folder.name}}.</h2>
				<hr class="colorgraph">

				{% if folder_taken %}
				<div class="alert alert-danger" role="alert">Folder name already exists. Please try again.</div>
				{% endif %}
				{% if form.name.errors %}
				<div class="alert alert-danger" role="alert">The folder name is required. Please try again.</div>
				{% endif %}		

				<div class="form-group">
				  <label for="id_name">Folder Name*:</label>
				  <input class="form-control input-lg" id="id_name" maxlength="128" name="name" type="text" value="{{folder.name}}" required="required"
					 {% if form.name.errors or folder_taken %} style="background:#ffdddd;" {% endif %}>
				</div>
				<div class="form-group">
				  <label for="id_location">Location:</label>
				  {{ form.location }}
				</div>
				<div class="form-group">
				  <label for="id_description">Description:</label>
				  {{ form.description }}
				</div>
				<hr class="colorgraph">
				<input type="submit" class="btn btn-lg btn-primary btn-block" formaction="{% url 'copy_folder' folder_id %}" value="Copy folder">
			</fieldset>
		</form>
    </div>
</div>

</div>

{% endblock %}

secure_witness/templates/secure_witness/edit_bulletin.html
{% extends "base.html" %}

{% block center_content %}
{% load staticfiles %}
<!-- Custom styles for this template -->
<link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

<div class="container">

<div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Edit the bulletin {{bulletin.name}}.</h2>
				<hr class="colorgraph">

				{% if bulletin_taken %}
				<div class="alert alert-danger" role="alert">Bulletin name already exists. Please try again.</div>
				{% endif %}
				{% if form.name.errors %}
				<div class="alert alert-danger" role="alert">The bulletin name is required. Please try again.</div>
				{% endif %}		

				<div class="form-group">
				  <label for="id_name">Bulletin Name*: </label>
				  <input class="form-control input-lg" id="id_name" maxlength="128" name="name" type="text" value="{{bulletin.name}}" required="required" 
					 {% if form.name.errors or bulletin_taken %} style="background:#ffdddd;" {% endif %}>
				</div>
				<div class="form-group">
				  <label for="id_location">Location:</label>
				  {{ form.location }}
				</div>
				<div class="form-group">
				  <label for="id_description">Description:</label>
				  {{ form.description }}
				</div>
				<hr class="colorgraph">
				    <input type="submit" class="btn btn-lg btn-primary btn-block" formaction="{% url 'edit_bulletin' bulletin_id %}" value="Update bulletin">
			</fieldset>
		</form>
    </div>
</div>

</div>

{% endblock %}

secure_witness/templates/secure_witness/edit_folder.html
{% extends "base.html" %}

{% block center_content %}

{% load staticfiles %}
<!-- Custom styles for this template -->
<link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

<div class="container">

<div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Edit the folder {{folder.name}}.</h2>
				<hr class="colorgraph">

				{% if folder_taken %}
				<div class="alert alert-danger" role="alert">Folder name already exists. Please try again.</div>
				{% endif %}
				{% if form.name.errors %}
				<div class="alert alert-danger" role="alert">The folder name is required. Please try again.</div>
				{% endif %}		

				<div class="form-group">
				  <label for="id_name">Folder Name*:</label>
				  <input class="form-control input-lg" id="id_name" maxlength="128" name="name" type="text" value="{{folder.name}}" required="required"
					 {% if form.name.errors or folder_taken %} style="background:#ffdddd;" {% endif %}>
				</div>
				<div class="form-group">
				  <label for="id_location">Location:</label>
				  {{ form.location }}
				</div>
				<div class="form-group">
				  <label for="id_description">Description:</label>
				  {{ form.description }}
				</div>
				<hr class="colorgraph">
				<input type="submit" class="btn btn-lg btn-primary btn-block" formaction="{% url 'edit_folder' folder_id %}" value="Update folder">
			</fieldset>
		</form>
    </div>
</div>

</div>

{% endblock %}

secure_witness/templates/secure_witness/file_password.html
{% extends "base.html" %}

{% block center_content %}

{% if no_access %}
<p><strong>You do not have permission to access this file.</strong></p>
{% else %}

{% if password_fail %}
<p><strong>Incorrect password. Please try again.</strong></p>
{% endif %}

<p>This file is encrypted. Please enter your password below to access this file.</p>
<form action="{% url 'get_file' file_id %}" method="post">
{% csrf_token %}
<p>Password: <input name="password" type="password" /></p>
<input type="submit" value="Download file" />
</form>

{% endif %}

{% endblock %}

secure_witness/templates/secure_witness/give_access.html
{% extends "base.html" %}

{% block center_content %}

{% if required_fields_missing %}
<p><strong>Error: You did not fill out a required field. Please try again.</strong></p>
{% endif %}

{% if password_incorrect %}
<p><strong>Error: Your password did not match. Please try again.</strong></p>
{% endif %}

<form id="id_form" action="{% url 'give_access' file.pk %}" method="post">
{% csrf_token %}
<p>Use the following form to select the user(s) to whom you would like to grant
   access to <strong>{{ file.name }}</strong>. You may select multiple users by
   holding the CTRL key while selecting.</p>
<p>{{ form.reader }}</p>
<p>Please enter your password to confirm your identity.</p>
<p>Password: {{ form.author_password }}</p>
<p><a href="#" onclick="javascript:{document.getElementById('id_form').submit();}">Grant access to these users</a></p>
</form>

{% endblock %}

secure_witness/templates/secure_witness/home.html
{% extends "base.html" %}

{% block center_content %}
{% load staticfiles %}
<link href="{% static 'secure_witness/layout.css' %}" rel="stylesheet" type="text/css" />

<title>Welcome to SecureWitness</title>

{% if logged_in %}
<h2><strong>Your Folders</strong></h2>
<br>
{% if folders|length == 0 %}
<h4>You have not created any folders!</h4>
<br><br>
<a class="btn btn-primary" href="{% url 'new_folder' %}">
  <span class="glyphicon glyphicon-plus"></span>Create new folder</a>
{% else %}
<a class="btn btn-primary" href="{% url 'new_folder' %}">
  <span class="glyphicon glyphicon-plus"></span>Create new folder</a>
<br><br>
<div class="container">
  <div class="row col-md-16 col-md-offset-15 custyle">
    <table class="table table-striped custab">
      <thead>
	<tr>
	  <th>Name</th>
	  <th>Location</th>
	  <th>Description</th>
	  <th class="text-center">Action</th>
	</tr>
      </thead>
      {% for folder in folders %}
      <tr>
        <td><a href="{% url 'get_folder' folder.pk %}">{{folder.name}}</a></td>
	{% if folder.location %}
        <td>{{folder.location}}</td>
	{% else %}
	<td>--</td>
	{% endif %}
	{% if folder.description %}
	<td>{{folder.description}}</td>
	{% else %}
	<td>--</td>
	{% endif %}
	<td class="text-center"><a class="btn btn-info" href="{% url 'edit_folder' folder.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
	  <a href="#" class="btn btn-danger" onclick="javascript:{if(confirm('Are you sure?'))window.location.href='{% url 'delete_folder' folder.pk %}';}">
	    <span class="glyphicon glyphicon-remove"></span>Delete</a>
	  <a href="{% url 'copy_folder' folder.pk %}" class="btn btn-warning">
	    <span class="glyphicon glyphicon-share"></span>Copy</a></td>
      </tr>
      {% endfor %}

    </table>
  </div>
</div>
{% endif %}
{% else %}
<link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

<div class="container">

<div class="row" style="margin-top:10px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Please Sign In</h2>
				<hr class="colorgraph">

				{% if account_disabled %}
				<div class="alert alert-danger" role="alert">Your account has been disabled. Please contact an administrator.</div>
				{% elif invalid_login %}
				<div class="alert alert-info" role="alert">Your username and password did not match. Please try again. </div>
				{% endif %}
		
				<div class="form-group">
				  <input type="text" name="username" id="username" class="form-control input-lg" placeholder="Username">
				</div>

				<div class="form-group">
				  <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password">
				</div>

				<span class="button-checkbox">
				  <a href="{% url 'new_user' %}" class="btn btn-info">Create new account</a>
				</span>

				<hr class="colorgraph">
				<input type="submit" class="btn btn-lg btn-success btn-block" formaction="{% url 'existing_user' %}" value="Sign In">
			</fieldset>
		</form>
    </div>
</div>

</div>

{% endif %}

{% endblock %}

secure_witness/templates/secure_witness/login.html
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>SecureWitness: Sign In</title>

    {% extends "base.html" %}
    {% load staticfiles %}
    {% block center_content %}

    <!-- Bootstrap core CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Custom styles for this template -->
    <link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

  </head>

  <body>

<div class="container">

<div class="row" style="margin-top:10px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Please Sign In</h2>
				<hr class="colorgraph">

				{% if account_disabled %}
				<div class="alert alert-danger" role="alert">Your account has been disabled. Please contact an administrator.</div>
				{% elif invalid_user %}
				<div class="alert alert-warning" role="alert">That username does not exist. Please create an account.</div>
				{% elif invalid_login %}
				<div class="alert alert-info" role="alert">Your username and password did not match. Please try again. </div>
				{% endif %}
		
				<div class="form-group">
				  <input type="text" name="username" id="username" class="form-control input-lg" placeholder="Username" required="required">
				</div>

				<div class="form-group">
				  <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" required="required">
				</div>

				<span class="button-checkbox">
				  <a href="{% url 'new_user' %}" class="btn btn-info">Create new account</a>
				</span>
				
				<hr class="colorgraph">
				<input type="submit" class="btn btn-lg btn-success btn-block" formaction="{% url 'existing_user' %}" value="Sign In">
				
			</fieldset>
		</form>
    </div>
</div>

</div>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
{% endblock %}

</html>

secure_witness/templates/secure_witness/my_files.html
{% extends "base.html" %}

{% block center_content %}
{% load staticfiles %}
<link href="{% static secure_witness/layout.css' %}" rel="stylesheet" type="text/css"/>

<title>My Files</title>

{% if logged_in %}
<h2>{{bulletin.name}}</h2>
<h3>Files</h3>

{% if files|length == 0 %}
<h4>No files inside of this bulletin!</h4>
<br><br>

{% if logged_in and bulletin.author == user %}
<a class="btn btn-primary" href="{% url 'new_file' %}">

<p><a href="{% url 'new_file' %}">Upload new file</a></p>
{% if files|length > 0 %}
<ul>
{% for file in files %}
<li><a href="{% url 'get_file' file.pk %}">{{ file.name }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>You have not uploaded any files!</p>
{% endif %}
{% endblock %}

secure_witness/templates/secure_witness/new_bulletin.html
{% extends "base.html" %}

{% block center_content %}
{% load staticfiles %}
<!-- Custom styles for this template -->
<link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

<div class="container">

<div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Create a new bulletin for {{folder.name}}</h2>
				<hr class="colorgraph">

				{% if bulletin_taken %}
				<div class="alert alert-danger" role="alert">Bulletin name already exists. Please try again.</div>
				{% endif %}
				{% if form.name.errors %}
				<div class="alert alert-danger" role="alert">The bulletin name is required. Please try again.</div>
				{% endif %}		

				<div class="form-group">
				  <label for="id_name">Bulletin Name*: </label>
				  <input class="form-control input-lg" id="id_name" maxlength="128" name="name" type="text" placeholder="New bulletin" required="required" 
					 {% if form.name.errors or bulletin_taken %} style="background:#ffdddd;" {% endif %}>
				</div>
				<div class="form-group">
				  <label for="id_location">Location:</label>
				  {{ form.location }}
				</div>
				<div class="form-group">
				  <label for="id_description">Description:</label>
				  {{ form.description }}
				</div>
				<hr class="colorgraph">
				    <input type="submit" class="btn btn-lg btn-primary btn-block" formaction="{% url 'new_bulletin' folder_id %}" value="Create bulletin">
			</fieldset>
		</form>
    </div>
</div>

</div>

{% endblock %}

secure_witness/templates/secure_witness/new_user.html
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>SecureWitness: Sign In</title>

    {% extends "base.html" %}
    {% load staticfiles %}
    {% block center_content %}

    <!-- Bootstrap core CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Custom styles for this template -->
    <link href="{% static 'secure_witness/signin2.css' %}" rel="stylesheet" type="text/css" />

  </head>

  <body>


<div class="container">

<div class="row" style="margin-top:10px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
		  {% csrf_token %}
			<fieldset>
				<h2>Create an account.</h2>
				<hr class="colorgraph">

				{% if username_fail %}
				<div class="alert alert-info" role="alert">That username is already taken. Please try again.</div>
				{% elif password_fail %}
				<div class="alert alert-info" role="alert">Your passwords did not match. Please try again.</div>
				{% endif %}
		
				<div class="form-group">
				  <input type="text" name="username" id="username" class="form-control input-lg" placeholder="Username" required="required">
				</div>
				<div class="form-group">
				  <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" required="required">
				</div>
				<div class="form-group">
				  <input type="password" name="confirm_password" id="confirm_password" class="form-control input-lg" placeholder="Confirm password" required="required">
				</div>
				<hr class="colorgraph">
				    <input type="submit" class="btn btn-lg btn-primary btn-block" formaction="{% url 'new_user' %}" value="Register">
			</fieldset>
		</form>
    </div>
</div>

</div>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
{% endblock %}

</html>

secure_witness/templates/secure_witness/search_bulletins_results.html
{% extends "base.html" %}

{% block center_content %}
<p>Your search returned <strong>{{ results|length }} result{{ results|length|pluralize }}</strong>.</p>
{% for bulletin in results %}
<div class="result">
<p><span style="font-size:130%;"><strong><a href="{% url 'get_bulletin' bulletin.pk %}">{{ bulletin.name }}</a></strong></span>
   <em>by {{ bulletin.author.username }}</em><br />
   <small>{{ bulletin.date_created }}
   (last modified {{ bulletin.date_modified }})</small></p>
{% if bulletin.description|length > 0 %}
<p>{{ bulletin.description }}</p>
{% else %}
<p><em>No description.</em></p>
{% endif %}
</div>
{% endfor %}
{% endblock %}